# # if(5>2):
# #     print("false")

# fruits = ["apple", "banana", "cherry"]
# x, y, z = fruits
# print(x)
# print(y)
# print(z)



# a=  1
# b = "3"
# c = (a + b) 
# print(c)


# name = "piyu"
# age = 19
# roll_no = 33
# std = 12
# full_details = "My name is {}, I am {} old. my roll no is {}, and i am in {}std. "

# print(full_details.format(name, age, roll_no, std))

# print(10 > 9)
# print(10 == 9)
# print(10 < 9) 

# fruits = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
# print(fruits[2:5])


#  F-STRINGS

name = "piyu"
age = 19
roll_no = 33
std = 12

print(f"your name is {name}, your roll no is {roll_no} and your are in { std}")